# -*- coding: utf-8 -*-
"""Question_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMSm1HgssuNfDdXtMTyeqCi9-D-uf8vQ

3.	Explain what a Kuwahara filter is, and apply it to the image using either Python or MATLAB to demonstrate its effect.

The **Kuwahara filter** is a smoothing filter that helps keep edges sharp. It divides the image into small regions, and for each region, it selects the part with the least variation to apply smoothing, preserving the edges in the process.
"""

!pip install pykuwahara

import cv2
from pykuwahara import kuwahara

# Load the image
image = cv2.imread('/content/lena.png')

# Apply Kuwahara filter using the mean method
filt1 = kuwahara(image, method='mean', radius=3)

# Apply Kuwahara filter using the Gaussian method
filt2 = kuwahara(image, method='gaussian', radius=3)  # default sigma: computed by OpenCV

# Save the filtered images
cv2.imwrite('lena-kfilt-mean.jpg', filt1)
cv2.imwrite('lena-kfilt-gaus.jpg', filt2)

# After saving the filtered images, print confirmation
print("Filtered images have been saved as 'lena-kfilt-mean.jpg' and 'lena-kfilt-gaus.jpg'.")

"""When you apply the Kuwahara filter using both the mean and Gaussian methods, the images will show different types of smoothing, while still preserving some edges.

Kuwahara Filter with Mean Method:

Appearance: The Kuwahara filter smooths the image while keeping edge details. It divides the image into small regions, finds the average in each, and assigns the central pixel the value from the region with the least variation. This reduces noise without blurring the edges too much.


Smooth Regions: In areas with even intensity, like backgrounds or smooth surfaces, the filter smooths the pixels, making the image appear softer and more uniform, almost like a painting.


Edge Preservation: The filter preserves sharp edges by focusing on areas with low variance. In contrast, the mean method can make the image look more "blocky" or simplified, unlike smoother filters like Gaussian blur.

Kuwahara Filter with Gaussian Method:


Appearance: The Gaussian method of the Kuwahara filter smooths the image by giving more weight to pixels near the center of each region. This results in smoother transitions between pixels and less blocky effects compared to the basic mean method.


Smooth Regions: Like the mean filter, the Gaussian filter smooths uniform areas of the image. However, it creates softer transitions between different regions, giving a more natural appearance compared to the mean filter.


Edge Preservation: The Gaussian filter keeps the edges but makes them softer compared to the mean filter. It smooths the image while gently blending regions, which is useful when you want to preserve edges without sharp transitions.
"""

